---
title: "R Notebook"
output: default
---

# library
```{r}
library(tm)
library(wordcloud)
library(wordcloud2)
library(syuzhet)
library(lubridate)
library(ggplot2)
library(scales)
library(reshape2)
library(dplyr)
```

# Data
```{r}
apple <- read.csv("D:/RFile/R study/SentimentAnalysis/apple.csv", header = T)

str(apple)
```

# Build corpus
```{r}
corpus <- iconv(apple$text, to = "UTF-8")
corpus <- Corpus(VectorSource(corpus))
inspect(corpus[1:5])
```

# Clean Text
```{r}
# change text to lower case
corpus <- tm_map(corpus, tolower)
inspect(corpus[1:5])

# remove punctuation
corpus <- tm_map(corpus, removePunctuation)
inspect(corpus[1:5])

# remove numbers
corpus <- tm_map(corpus, removeNumbers)
inspect(corpus[1:5])

# taking some words which are has less impact
cleanset <- tm_map(corpus, removeWords, stopwords('english'))
inspect(cleanset[1:5])

# remove url 
removeURL <- function(x) gsub('http[[:alnum:]]*', '', x)
cleanset <- tm_map(cleanset, content_transformer(removeURL))
inspect(cleanset[1:5])

# remove space
cleanset <- tm_map(cleanset, removeWords, c('aapl', 'apple'))
cleanset <- tm_map(cleanset, gsub,
                   pattern = 'stocks',
                   replacement = 'stock')
cleanset <- tm_map(cleanset, stripWhitespace)
cleanset <- tm_map(cleanset, removePunctuation)

inspect(cleanset[1:5])
```

# Term document matrix
```{r}
tdm <- TermDocumentMatrix(cleanset)
#tdm
tdm <- as.matrix(tdm)
tdm[1:10, 1:20]
```

# Bar plot
```{r}
w <- rowSums(tdm)
w <- subset(w, w >= 25)
barplot(w,
        las = 2,
        col = rainbow(50))
```

# WordCloud
```{r warning=FALSE}
w <- sort(rowSums(tdm), decreasing = TRUE)
set.seed(222)
wordcloud(words = names(w),
          freq = w,
          max.words = 150,
          random.order = F,
          min.freq = 5,
          colors = brewer.pal(8, 'Dark2'),
          scale = c(5, 0.3),
          rot.per = 0.3)

```

# Wordcloud2
```{r}
w <- data.frame(names(w), w)
colnames(w) <- c('Word', 'freq')
# head(w)
wordcloud2(w, 
           size = 0.7,
           shape = "star",
           rotateRatio = 0.5,
           minSize = 1)

# letterCloud(w,
#             word = "apple",
#             size = 0.3)
# Dont know why can not plot the correct graph.
```

# sentiment analysis
```{r}
# read file
apple <- read.csv(file.choose(), header = T)
tweets <- iconv(apple$text, to = "UTF-8")

# Obtain sentiment scores
s <- get_nrc_sentiment(tweets)
head(s)
tweets[4]
get_nrc_sentiment("delay")

# Barplot
barplot(colSums(s),
        las = 2,
        col = rainbow(10),
        ylab = "Count",
        main = "Sentiment Scores for Apple Tweets")
```

